/* 
 * Camunda BPM REST API
 *
 * OpenApi Spec for Camunda BPM REST API.
 *
 * The version of the OpenAPI document: 7.13.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing ActivityStatisticsResultDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ActivityStatisticsResultDtoTests
    {
        // TODO uncomment below to declare an instance variable for ActivityStatisticsResultDto
        //private ActivityStatisticsResultDto instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ActivityStatisticsResultDto
            //instance = new ActivityStatisticsResultDto();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ActivityStatisticsResultDto
        /// </summary>
        [Test]
        public void ActivityStatisticsResultDtoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" ActivityStatisticsResultDto
            //Assert.IsInstanceOf(typeof(ActivityStatisticsResultDto), instance);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Instances'
        /// </summary>
        [Test]
        public void InstancesTest()
        {
            // TODO unit test for the property 'Instances'
        }
        /// <summary>
        /// Test the property 'FailedJobs'
        /// </summary>
        [Test]
        public void FailedJobsTest()
        {
            // TODO unit test for the property 'FailedJobs'
        }
        /// <summary>
        /// Test the property 'Incidents'
        /// </summary>
        [Test]
        public void IncidentsTest()
        {
            // TODO unit test for the property 'Incidents'
        }

    }

}
