/* 
 * Camunda BPM REST API
 *
 * OpenApi Spec for Camunda BPM REST API.
 *
 * The version of the OpenAPI document: 7.13.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing CompleteTaskDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CompleteTaskDtoTests
    {
        // TODO uncomment below to declare an instance variable for CompleteTaskDto
        //private CompleteTaskDto instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CompleteTaskDto
            //instance = new CompleteTaskDto();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CompleteTaskDto
        /// </summary>
        [Test]
        public void CompleteTaskDtoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" CompleteTaskDto
            //Assert.IsInstanceOf(typeof(CompleteTaskDto), instance);
        }


        /// <summary>
        /// Test the property 'Variables'
        /// </summary>
        [Test]
        public void VariablesTest()
        {
            // TODO unit test for the property 'Variables'
        }
        /// <summary>
        /// Test the property 'WithVariablesInReturn'
        /// </summary>
        [Test]
        public void WithVariablesInReturnTest()
        {
            // TODO unit test for the property 'WithVariablesInReturn'
        }

    }

}
