/* 
 * Camunda BPM REST API
 *
 * OpenApi Spec for Camunda BPM REST API.
 *
 * The version of the OpenAPI document: 7.13.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing ExternalTaskQueryDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ExternalTaskQueryDtoTests
    {
        // TODO uncomment below to declare an instance variable for ExternalTaskQueryDto
        //private ExternalTaskQueryDto instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ExternalTaskQueryDto
            //instance = new ExternalTaskQueryDto();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ExternalTaskQueryDto
        /// </summary>
        [Test]
        public void ExternalTaskQueryDtoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" ExternalTaskQueryDto
            //Assert.IsInstanceOf(typeof(ExternalTaskQueryDto), instance);
        }


        /// <summary>
        /// Test the property 'ExternalTaskId'
        /// </summary>
        [Test]
        public void ExternalTaskIdTest()
        {
            // TODO unit test for the property 'ExternalTaskId'
        }
        /// <summary>
        /// Test the property 'ExternalTaskIdIn'
        /// </summary>
        [Test]
        public void ExternalTaskIdInTest()
        {
            // TODO unit test for the property 'ExternalTaskIdIn'
        }
        /// <summary>
        /// Test the property 'TopicName'
        /// </summary>
        [Test]
        public void TopicNameTest()
        {
            // TODO unit test for the property 'TopicName'
        }
        /// <summary>
        /// Test the property 'WorkerId'
        /// </summary>
        [Test]
        public void WorkerIdTest()
        {
            // TODO unit test for the property 'WorkerId'
        }
        /// <summary>
        /// Test the property 'Locked'
        /// </summary>
        [Test]
        public void LockedTest()
        {
            // TODO unit test for the property 'Locked'
        }
        /// <summary>
        /// Test the property 'NotLocked'
        /// </summary>
        [Test]
        public void NotLockedTest()
        {
            // TODO unit test for the property 'NotLocked'
        }
        /// <summary>
        /// Test the property 'WithRetriesLeft'
        /// </summary>
        [Test]
        public void WithRetriesLeftTest()
        {
            // TODO unit test for the property 'WithRetriesLeft'
        }
        /// <summary>
        /// Test the property 'NoRetriesLeft'
        /// </summary>
        [Test]
        public void NoRetriesLeftTest()
        {
            // TODO unit test for the property 'NoRetriesLeft'
        }
        /// <summary>
        /// Test the property 'LockExpirationAfter'
        /// </summary>
        [Test]
        public void LockExpirationAfterTest()
        {
            // TODO unit test for the property 'LockExpirationAfter'
        }
        /// <summary>
        /// Test the property 'LockExpirationBefore'
        /// </summary>
        [Test]
        public void LockExpirationBeforeTest()
        {
            // TODO unit test for the property 'LockExpirationBefore'
        }
        /// <summary>
        /// Test the property 'ActivityId'
        /// </summary>
        [Test]
        public void ActivityIdTest()
        {
            // TODO unit test for the property 'ActivityId'
        }
        /// <summary>
        /// Test the property 'ActivityIdIn'
        /// </summary>
        [Test]
        public void ActivityIdInTest()
        {
            // TODO unit test for the property 'ActivityIdIn'
        }
        /// <summary>
        /// Test the property 'ExecutionId'
        /// </summary>
        [Test]
        public void ExecutionIdTest()
        {
            // TODO unit test for the property 'ExecutionId'
        }
        /// <summary>
        /// Test the property 'ProcessInstanceId'
        /// </summary>
        [Test]
        public void ProcessInstanceIdTest()
        {
            // TODO unit test for the property 'ProcessInstanceId'
        }
        /// <summary>
        /// Test the property 'ProcessInstanceIdIn'
        /// </summary>
        [Test]
        public void ProcessInstanceIdInTest()
        {
            // TODO unit test for the property 'ProcessInstanceIdIn'
        }
        /// <summary>
        /// Test the property 'ProcessDefinitionId'
        /// </summary>
        [Test]
        public void ProcessDefinitionIdTest()
        {
            // TODO unit test for the property 'ProcessDefinitionId'
        }
        /// <summary>
        /// Test the property 'TenantIdIn'
        /// </summary>
        [Test]
        public void TenantIdInTest()
        {
            // TODO unit test for the property 'TenantIdIn'
        }
        /// <summary>
        /// Test the property 'Active'
        /// </summary>
        [Test]
        public void ActiveTest()
        {
            // TODO unit test for the property 'Active'
        }
        /// <summary>
        /// Test the property 'Suspended'
        /// </summary>
        [Test]
        public void SuspendedTest()
        {
            // TODO unit test for the property 'Suspended'
        }
        /// <summary>
        /// Test the property 'PriorityHigherThanOrEquals'
        /// </summary>
        [Test]
        public void PriorityHigherThanOrEqualsTest()
        {
            // TODO unit test for the property 'PriorityHigherThanOrEquals'
        }
        /// <summary>
        /// Test the property 'PriorityLowerThanOrEquals'
        /// </summary>
        [Test]
        public void PriorityLowerThanOrEqualsTest()
        {
            // TODO unit test for the property 'PriorityLowerThanOrEquals'
        }
        /// <summary>
        /// Test the property 'Sorting'
        /// </summary>
        [Test]
        public void SortingTest()
        {
            // TODO unit test for the property 'Sorting'
        }

    }

}
