/* 
 * Camunda BPM REST API
 *
 * OpenApi Spec for Camunda BPM REST API.
 *
 * The version of the OpenAPI document: 7.13.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing IncidentStatisticsResultDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class IncidentStatisticsResultDtoTests
    {
        // TODO uncomment below to declare an instance variable for IncidentStatisticsResultDto
        //private IncidentStatisticsResultDto instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of IncidentStatisticsResultDto
            //instance = new IncidentStatisticsResultDto();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of IncidentStatisticsResultDto
        /// </summary>
        [Test]
        public void IncidentStatisticsResultDtoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" IncidentStatisticsResultDto
            //Assert.IsInstanceOf(typeof(IncidentStatisticsResultDto), instance);
        }


        /// <summary>
        /// Test the property 'IncidentType'
        /// </summary>
        [Test]
        public void IncidentTypeTest()
        {
            // TODO unit test for the property 'IncidentType'
        }
        /// <summary>
        /// Test the property 'IncidentCount'
        /// </summary>
        [Test]
        public void IncidentCountTest()
        {
            // TODO unit test for the property 'IncidentCount'
        }

    }

}
