/* 
 * Camunda BPM REST API
 *
 * OpenApi Spec for Camunda BPM REST API.
 *
 * The version of the OpenAPI document: 7.13.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing MissingAuthorizationDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class MissingAuthorizationDtoTests
    {
        // TODO uncomment below to declare an instance variable for MissingAuthorizationDto
        //private MissingAuthorizationDto instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of MissingAuthorizationDto
            //instance = new MissingAuthorizationDto();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of MissingAuthorizationDto
        /// </summary>
        [Test]
        public void MissingAuthorizationDtoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" MissingAuthorizationDto
            //Assert.IsInstanceOf(typeof(MissingAuthorizationDto), instance);
        }


        /// <summary>
        /// Test the property 'PermissionName'
        /// </summary>
        [Test]
        public void PermissionNameTest()
        {
            // TODO unit test for the property 'PermissionName'
        }
        /// <summary>
        /// Test the property 'ResourceName'
        /// </summary>
        [Test]
        public void ResourceNameTest()
        {
            // TODO unit test for the property 'ResourceName'
        }
        /// <summary>
        /// Test the property 'ResourceId'
        /// </summary>
        [Test]
        public void ResourceIdTest()
        {
            // TODO unit test for the property 'ResourceId'
        }

    }

}
