/* 
 * Camunda BPM REST API
 *
 * OpenApi Spec for Camunda BPM REST API.
 *
 * The version of the OpenAPI document: 7.13.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing PatchVariablesDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PatchVariablesDtoTests
    {
        // TODO uncomment below to declare an instance variable for PatchVariablesDto
        //private PatchVariablesDto instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of PatchVariablesDto
            //instance = new PatchVariablesDto();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of PatchVariablesDto
        /// </summary>
        [Test]
        public void PatchVariablesDtoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" PatchVariablesDto
            //Assert.IsInstanceOf(typeof(PatchVariablesDto), instance);
        }


        /// <summary>
        /// Test the property 'Modifications'
        /// </summary>
        [Test]
        public void ModificationsTest()
        {
            // TODO unit test for the property 'Modifications'
        }
        /// <summary>
        /// Test the property 'Deletions'
        /// </summary>
        [Test]
        public void DeletionsTest()
        {
            // TODO unit test for the property 'Deletions'
        }

    }

}
