/* 
 * Camunda BPM REST API
 *
 * OpenApi Spec for Camunda BPM REST API.
 *
 * The version of the OpenAPI document: 7.13.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing ProblemDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ProblemDtoTests
    {
        // TODO uncomment below to declare an instance variable for ProblemDto
        //private ProblemDto instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ProblemDto
            //instance = new ProblemDto();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ProblemDto
        /// </summary>
        [Test]
        public void ProblemDtoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" ProblemDto
            //Assert.IsInstanceOf(typeof(ProblemDto), instance);
        }


        /// <summary>
        /// Test the property 'Message'
        /// </summary>
        [Test]
        public void MessageTest()
        {
            // TODO unit test for the property 'Message'
        }
        /// <summary>
        /// Test the property 'Line'
        /// </summary>
        [Test]
        public void LineTest()
        {
            // TODO unit test for the property 'Line'
        }
        /// <summary>
        /// Test the property 'Column'
        /// </summary>
        [Test]
        public void ColumnTest()
        {
            // TODO unit test for the property 'Column'
        }
        /// <summary>
        /// Test the property 'MainElementId'
        /// </summary>
        [Test]
        public void MainElementIdTest()
        {
            // TODO unit test for the property 'MainElementId'
        }
        /// <summary>
        /// Test the property 'ElementIds'
        /// </summary>
        [Test]
        public void ElementIdsTest()
        {
            // TODO unit test for the property 'ElementIds'
        }

    }

}
