/* 
 * Camunda BPM REST API
 *
 * OpenApi Spec for Camunda BPM REST API.
 *
 * The version of the OpenAPI document: 7.13.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing ProcessDefinitionDiagramDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ProcessDefinitionDiagramDtoTests
    {
        // TODO uncomment below to declare an instance variable for ProcessDefinitionDiagramDto
        //private ProcessDefinitionDiagramDto instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ProcessDefinitionDiagramDto
            //instance = new ProcessDefinitionDiagramDto();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ProcessDefinitionDiagramDto
        /// </summary>
        [Test]
        public void ProcessDefinitionDiagramDtoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" ProcessDefinitionDiagramDto
            //Assert.IsInstanceOf(typeof(ProcessDefinitionDiagramDto), instance);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Bpmn20Xml'
        /// </summary>
        [Test]
        public void Bpmn20XmlTest()
        {
            // TODO unit test for the property 'Bpmn20Xml'
        }

    }

}
