/* 
 * Camunda BPM REST API
 *
 * OpenApi Spec for Camunda BPM REST API.
 *
 * The version of the OpenAPI document: 7.13.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing ProcessInstanceModificationDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ProcessInstanceModificationDtoTests
    {
        // TODO uncomment below to declare an instance variable for ProcessInstanceModificationDto
        //private ProcessInstanceModificationDto instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ProcessInstanceModificationDto
            //instance = new ProcessInstanceModificationDto();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ProcessInstanceModificationDto
        /// </summary>
        [Test]
        public void ProcessInstanceModificationDtoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" ProcessInstanceModificationDto
            //Assert.IsInstanceOf(typeof(ProcessInstanceModificationDto), instance);
        }


        /// <summary>
        /// Test the property 'SkipCustomListeners'
        /// </summary>
        [Test]
        public void SkipCustomListenersTest()
        {
            // TODO unit test for the property 'SkipCustomListeners'
        }
        /// <summary>
        /// Test the property 'SkipIoMappings'
        /// </summary>
        [Test]
        public void SkipIoMappingsTest()
        {
            // TODO unit test for the property 'SkipIoMappings'
        }
        /// <summary>
        /// Test the property 'Instructions'
        /// </summary>
        [Test]
        public void InstructionsTest()
        {
            // TODO unit test for the property 'Instructions'
        }
        /// <summary>
        /// Test the property 'Annotation'
        /// </summary>
        [Test]
        public void AnnotationTest()
        {
            // TODO unit test for the property 'Annotation'
        }

    }

}
