/* 
 * Camunda BPM REST API
 *
 * OpenApi Spec for Camunda BPM REST API.
 *
 * The version of the OpenAPI document: 7.13.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing SortTaskQueryParametersDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SortTaskQueryParametersDtoTests
    {
        // TODO uncomment below to declare an instance variable for SortTaskQueryParametersDto
        //private SortTaskQueryParametersDto instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of SortTaskQueryParametersDto
            //instance = new SortTaskQueryParametersDto();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SortTaskQueryParametersDto
        /// </summary>
        [Test]
        public void SortTaskQueryParametersDtoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" SortTaskQueryParametersDto
            //Assert.IsInstanceOf(typeof(SortTaskQueryParametersDto), instance);
        }


        /// <summary>
        /// Test the property 'Variable'
        /// </summary>
        [Test]
        public void VariableTest()
        {
            // TODO unit test for the property 'Variable'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Test]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

    }

}
