/* 
 * Camunda BPM REST API
 *
 * OpenApi Spec for Camunda BPM REST API.
 *
 * The version of the OpenAPI document: 7.13.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing StartProcessInstanceDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class StartProcessInstanceDtoTests
    {
        // TODO uncomment below to declare an instance variable for StartProcessInstanceDto
        //private StartProcessInstanceDto instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of StartProcessInstanceDto
            //instance = new StartProcessInstanceDto();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of StartProcessInstanceDto
        /// </summary>
        [Test]
        public void StartProcessInstanceDtoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" StartProcessInstanceDto
            //Assert.IsInstanceOf(typeof(StartProcessInstanceDto), instance);
        }


        /// <summary>
        /// Test the property 'BusinessKey'
        /// </summary>
        [Test]
        public void BusinessKeyTest()
        {
            // TODO unit test for the property 'BusinessKey'
        }
        /// <summary>
        /// Test the property 'Variables'
        /// </summary>
        [Test]
        public void VariablesTest()
        {
            // TODO unit test for the property 'Variables'
        }
        /// <summary>
        /// Test the property 'CaseInstanceId'
        /// </summary>
        [Test]
        public void CaseInstanceIdTest()
        {
            // TODO unit test for the property 'CaseInstanceId'
        }
        /// <summary>
        /// Test the property 'StartInstructions'
        /// </summary>
        [Test]
        public void StartInstructionsTest()
        {
            // TODO unit test for the property 'StartInstructions'
        }
        /// <summary>
        /// Test the property 'SkipCustomListeners'
        /// </summary>
        [Test]
        public void SkipCustomListenersTest()
        {
            // TODO unit test for the property 'SkipCustomListeners'
        }
        /// <summary>
        /// Test the property 'SkipIoMappings'
        /// </summary>
        [Test]
        public void SkipIoMappingsTest()
        {
            // TODO unit test for the property 'SkipIoMappings'
        }
        /// <summary>
        /// Test the property 'WithVariablesInReturn'
        /// </summary>
        [Test]
        public void WithVariablesInReturnTest()
        {
            // TODO unit test for the property 'WithVariablesInReturn'
        }

    }

}
