# coding: utf-8

"""
    Camunda BPM REST API

    OpenApi Spec for Camunda BPM REST API.  # noqa: E501

    The version of the OpenAPI document: 7.13.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.models.correlation_message_dto import CorrelationMessageDto  # noqa: E501
from openapi_client.rest import ApiException

class TestCorrelationMessageDto(unittest.TestCase):
    """CorrelationMessageDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test CorrelationMessageDto
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = openapi_client.models.correlation_message_dto.CorrelationMessageDto()  # noqa: E501
        if include_optional :
            return CorrelationMessageDto(
                message_name = '0', 
                business_key = '0', 
                tenant_id = '0', 
                without_tenant_id = True, 
                process_instance_id = '0', 
                correlation_keys = {
                    'key' : openapi_client.models.variable_value_dto.VariableValueDto(
                        value = openapi_client.models.value.value(), 
                        type = '0', 
                        value_info = { }, )
                    }, 
                local_correlation_keys = {
                    'key' : openapi_client.models.variable_value_dto.VariableValueDto(
                        value = openapi_client.models.value.value(), 
                        type = '0', 
                        value_info = { }, )
                    }, 
                process_variables = {
                    'key' : openapi_client.models.variable_value_dto.VariableValueDto(
                        value = openapi_client.models.value.value(), 
                        type = '0', 
                        value_info = { }, )
                    }, 
                process_variables_local = {
                    'key' : openapi_client.models.variable_value_dto.VariableValueDto(
                        value = openapi_client.models.value.value(), 
                        type = '0', 
                        value_info = { }, )
                    }, 
                all = True, 
                result_enabled = True, 
                variables_in_result_enabled = True
            )
        else :
            return CorrelationMessageDto(
        )

    def testCorrelationMessageDto(self):
        """Test CorrelationMessageDto"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
