# coding: utf-8

"""
    Camunda BPM REST API

    OpenApi Spec for Camunda BPM REST API.  # noqa: E501

    The version of the OpenAPI document: 7.13.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.models.activity_instance_incident_dto import ActivityInstanceIncidentDto  # noqa: E501
from openapi_client.rest import ApiException

class TestActivityInstanceIncidentDto(unittest.TestCase):
    """ActivityInstanceIncidentDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test ActivityInstanceIncidentDto
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = openapi_client.models.activity_instance_incident_dto.ActivityInstanceIncidentDto()  # noqa: E501
        if include_optional :
            return ActivityInstanceIncidentDto(
                id = '0', 
                parent_activity_instance_id = '0'
            )
        else :
            return ActivityInstanceIncidentDto(
        )

    def testActivityInstanceIncidentDto(self):
        """Test ActivityInstanceIncidentDto"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
