# coding: utf-8

"""
    Camunda BPM REST API

    OpenApi Spec for Camunda BPM REST API.  # noqa: E501

    The version of the OpenAPI document: 7.13.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.models.event_subscription_query_dto import EventSubscriptionQueryDto  # noqa: E501
from openapi_client.rest import ApiException

class TestEventSubscriptionQueryDto(unittest.TestCase):
    """EventSubscriptionQueryDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test EventSubscriptionQueryDto
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = openapi_client.models.event_subscription_query_dto.EventSubscriptionQueryDto()  # noqa: E501
        if include_optional :
            return EventSubscriptionQueryDto(
                event_subscription_id = '0', 
                event_name = '0', 
                event_type = 'message', 
                execution_id = '0', 
                process_instance_id = '0', 
                activity_id = '0', 
                tenant_id_in = [
                    '0'
                    ], 
                without_tenant_id = True, 
                include_event_subscriptions_without_tenant_id = True, 
                sorting = [
                    openapi_client.models.event_subscription_query_dto_sorting.EventSubscriptionQueryDto_sorting(
                        sort_by = 'created', 
                        sort_order = 'asc', )
                    ]
            )
        else :
            return EventSubscriptionQueryDto(
        )

    def testEventSubscriptionQueryDto(self):
        """Test EventSubscriptionQueryDto"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
