# coding: utf-8

"""
    Camunda BPM REST API

    OpenApi Spec for Camunda BPM REST API.  # noqa: E501

    The version of the OpenAPI document: 7.13.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.api.task_comment_api import TaskCommentApi  # noqa: E501
from openapi_client.rest import ApiException


class TestTaskCommentApi(unittest.TestCase):
    """TaskCommentApi unit test stubs"""

    def setUp(self):
        self.api = openapi_client.api.task_comment_api.TaskCommentApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_comment(self):
        """Test case for create_comment

        """
        pass

    def test_get_comment(self):
        """Test case for get_comment

        """
        pass

    def test_get_comments(self):
        """Test case for get_comments

        """
        pass


if __name__ == '__main__':
    unittest.main()
