# coding: utf-8

"""
    Camunda BPM REST API

    OpenApi Spec for Camunda BPM REST API.  # noqa: E501

    The version of the OpenAPI document: 7.13.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from openapi_client.configuration import Configuration


class ProcessDefinitionDiagramDto(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'id': 'str',
        'bpmn20_xml': 'str'
    }

    attribute_map = {
        'id': 'id',
        'bpmn20_xml': 'bpmn20Xml'
    }

    def __init__(self, id=None, bpmn20_xml=None, local_vars_configuration=None):  # noqa: E501
        """ProcessDefinitionDiagramDto - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._id = None
        self._bpmn20_xml = None
        self.discriminator = None

        if id is not None:
            self.id = id
        if bpmn20_xml is not None:
            self.bpmn20_xml = bpmn20_xml

    @property
    def id(self):
        """Gets the id of this ProcessDefinitionDiagramDto.  # noqa: E501

        The id of the process definition.  # noqa: E501

        :return: The id of this ProcessDefinitionDiagramDto.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this ProcessDefinitionDiagramDto.

        The id of the process definition.  # noqa: E501

        :param id: The id of this ProcessDefinitionDiagramDto.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def bpmn20_xml(self):
        """Gets the bpmn20_xml of this ProcessDefinitionDiagramDto.  # noqa: E501

        An escaped XML string containing the XML that this definition was deployed with. Carriage returns, line feeds and quotation marks are escaped.  # noqa: E501

        :return: The bpmn20_xml of this ProcessDefinitionDiagramDto.  # noqa: E501
        :rtype: str
        """
        return self._bpmn20_xml

    @bpmn20_xml.setter
    def bpmn20_xml(self, bpmn20_xml):
        """Sets the bpmn20_xml of this ProcessDefinitionDiagramDto.

        An escaped XML string containing the XML that this definition was deployed with. Carriage returns, line feeds and quotation marks are escaped.  # noqa: E501

        :param bpmn20_xml: The bpmn20_xml of this ProcessDefinitionDiagramDto.  # noqa: E501
        :type: str
        """

        self._bpmn20_xml = bpmn20_xml

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ProcessDefinitionDiagramDto):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ProcessDefinitionDiagramDto):
            return True

        return self.to_dict() != other.to_dict()
