/* 
 * Camunda BPM REST API
 *
 * OpenApi Spec for Camunda BPM REST API.
 *
 * The version of the OpenAPI document: 7.13.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using Org.OpenAPITools.Client;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing TaskIdentityLinkApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class TaskIdentityLinkApiTests
    {
        private TaskIdentityLinkApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new TaskIdentityLinkApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TaskIdentityLinkApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOf' TaskIdentityLinkApi
            //Assert.IsInstanceOf(typeof(TaskIdentityLinkApi), instance);
        }

        
        /// <summary>
        /// Test AddIdentityLink
        /// </summary>
        [Test]
        public void AddIdentityLinkTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //IdentityLinkDto identityLinkDto = null;
            //instance.AddIdentityLink(id, identityLinkDto);
            
        }
        
        /// <summary>
        /// Test DeleteIdentityLink
        /// </summary>
        [Test]
        public void DeleteIdentityLinkTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //IdentityLinkDto identityLinkDto = null;
            //instance.DeleteIdentityLink(id, identityLinkDto);
            
        }
        
        /// <summary>
        /// Test GetIdentityLinks
        /// </summary>
        [Test]
        public void GetIdentityLinksTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //string type = null;
            //var response = instance.GetIdentityLinks(id, type);
            //Assert.IsInstanceOf(typeof(List<IdentityLinkDto>), response, "response is List<IdentityLinkDto>");
        }
        
    }

}
